name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      - name: Run E2E on Chrome ğŸŒ
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          browser: chrome
          working-directory: ./app
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"

      - name: Run Component tests ğŸ§ª
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          install: false
          working-directory: ./app
          component: true
